server:
  port: 8080

application:
  security:
    jwt:
      secret-key: McvbIKwPaVjhmKBwFUdHDXzvFweAZgaJ8XJr6cBsvNkPI9VUvAWW7GzFMV6ZhHsI
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jugadores-api
    username: postgres
    password: 123
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  sql:
    init:
      mode: always

#logging:
#  level:
#    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

